/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSetoresIndexRouteImport } from './routes/_authenticated/setores.index'
import { Route as AuthenticatedOrdensIndexRouteImport } from './routes/_authenticated/ordens.index'
import { Route as AuthenticatedFornecedoresIndexRouteImport } from './routes/_authenticated/fornecedores.index'
import { Route as AuthenticatedEquipamentosIndexRouteImport } from './routes/_authenticated/equipamentos.index'
import { Route as AuthenticatedOrdensNovaRouteImport } from './routes/_authenticated/ordens.nova'
import { Route as AuthenticatedOrdensIdRouteImport } from './routes/_authenticated/ordens.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetoresIndexRoute =
  AuthenticatedSetoresIndexRouteImport.update({
    id: '/setores/',
    path: '/setores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdensIndexRoute =
  AuthenticatedOrdensIndexRouteImport.update({
    id: '/ordens/',
    path: '/ordens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFornecedoresIndexRoute =
  AuthenticatedFornecedoresIndexRouteImport.update({
    id: '/fornecedores/',
    path: '/fornecedores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipamentosIndexRoute =
  AuthenticatedEquipamentosIndexRouteImport.update({
    id: '/equipamentos/',
    path: '/equipamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdensNovaRoute = AuthenticatedOrdensNovaRouteImport.update({
  id: '/ordens/nova',
  path: '/ordens/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdensIdRoute = AuthenticatedOrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/ordens/nova': typeof AuthenticatedOrdensNovaRoute
  '/equipamentos/': typeof AuthenticatedEquipamentosIndexRoute
  '/fornecedores/': typeof AuthenticatedFornecedoresIndexRoute
  '/ordens/': typeof AuthenticatedOrdensIndexRoute
  '/setores/': typeof AuthenticatedSetoresIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/ordens/nova': typeof AuthenticatedOrdensNovaRoute
  '/equipamentos': typeof AuthenticatedEquipamentosIndexRoute
  '/fornecedores': typeof AuthenticatedFornecedoresIndexRoute
  '/ordens': typeof AuthenticatedOrdensIndexRoute
  '/setores': typeof AuthenticatedSetoresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/_authenticated/ordens/nova': typeof AuthenticatedOrdensNovaRoute
  '/_authenticated/equipamentos/': typeof AuthenticatedEquipamentosIndexRoute
  '/_authenticated/fornecedores/': typeof AuthenticatedFornecedoresIndexRoute
  '/_authenticated/ordens/': typeof AuthenticatedOrdensIndexRoute
  '/_authenticated/setores/': typeof AuthenticatedSetoresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ordens/$id'
    | '/ordens/nova'
    | '/equipamentos/'
    | '/fornecedores/'
    | '/ordens/'
    | '/setores/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/ordens/$id'
    | '/ordens/nova'
    | '/equipamentos'
    | '/fornecedores'
    | '/ordens'
    | '/setores'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/_authenticated/ordens/$id'
    | '/_authenticated/ordens/nova'
    | '/_authenticated/equipamentos/'
    | '/_authenticated/fornecedores/'
    | '/_authenticated/ordens/'
    | '/_authenticated/setores/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setores/': {
      id: '/_authenticated/setores/'
      path: '/setores'
      fullPath: '/setores/'
      preLoaderRoute: typeof AuthenticatedSetoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens/': {
      id: '/_authenticated/ordens/'
      path: '/ordens'
      fullPath: '/ordens/'
      preLoaderRoute: typeof AuthenticatedOrdensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores/': {
      id: '/_authenticated/fornecedores/'
      path: '/fornecedores'
      fullPath: '/fornecedores/'
      preLoaderRoute: typeof AuthenticatedFornecedoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos/': {
      id: '/_authenticated/equipamentos/'
      path: '/equipamentos'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof AuthenticatedEquipamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens/nova': {
      id: '/_authenticated/ordens/nova'
      path: '/ordens/nova'
      fullPath: '/ordens/nova'
      preLoaderRoute: typeof AuthenticatedOrdensNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens/$id': {
      id: '/_authenticated/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AuthenticatedOrdensIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedOrdensIdRoute: typeof AuthenticatedOrdensIdRoute
  AuthenticatedOrdensNovaRoute: typeof AuthenticatedOrdensNovaRoute
  AuthenticatedEquipamentosIndexRoute: typeof AuthenticatedEquipamentosIndexRoute
  AuthenticatedFornecedoresIndexRoute: typeof AuthenticatedFornecedoresIndexRoute
  AuthenticatedOrdensIndexRoute: typeof AuthenticatedOrdensIndexRoute
  AuthenticatedSetoresIndexRoute: typeof AuthenticatedSetoresIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedOrdensIdRoute: AuthenticatedOrdensIdRoute,
  AuthenticatedOrdensNovaRoute: AuthenticatedOrdensNovaRoute,
  AuthenticatedEquipamentosIndexRoute: AuthenticatedEquipamentosIndexRoute,
  AuthenticatedFornecedoresIndexRoute: AuthenticatedFornecedoresIndexRoute,
  AuthenticatedOrdensIndexRoute: AuthenticatedOrdensIndexRoute,
  AuthenticatedSetoresIndexRoute: AuthenticatedSetoresIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
