/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedUsuariosIndexRouteImport } from './routes/_authenticated/usuarios.index'
import { Route as AuthenticatedSetoresIndexRouteImport } from './routes/_authenticated/setores.index'
import { Route as AuthenticatedOrdensIndexRouteImport } from './routes/_authenticated/ordens.index'
import { Route as AuthenticatedManutencoesIndexRouteImport } from './routes/_authenticated/manutencoes.index'
import { Route as AuthenticatedFornecedoresIndexRouteImport } from './routes/_authenticated/fornecedores.index'
import { Route as AuthenticatedEquipamentosIndexRouteImport } from './routes/_authenticated/equipamentos.index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes.index'
import { Route as AuthenticatedOrdensNovaRouteImport } from './routes/_authenticated/ordens.nova'
import { Route as AuthenticatedOrdensIdRouteImport } from './routes/_authenticated/ordens.$id'
import { Route as AuthenticatedManutencoesIdRouteImport } from './routes/_authenticated/manutencoes.$id'
import { Route as AuthenticatedEquipamentosIdRouteImport } from './routes/_authenticated/equipamentos.$id'
import { Route as ApiPublicHooksNotificacoesRouteImport } from './routes/api/public/hooks/notificacoes'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsuariosIndexRoute =
  AuthenticatedUsuariosIndexRouteImport.update({
    id: '/usuarios/',
    path: '/usuarios/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSetoresIndexRoute =
  AuthenticatedSetoresIndexRouteImport.update({
    id: '/setores/',
    path: '/setores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdensIndexRoute =
  AuthenticatedOrdensIndexRouteImport.update({
    id: '/ordens/',
    path: '/ordens/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedManutencoesIndexRoute =
  AuthenticatedManutencoesIndexRouteImport.update({
    id: '/manutencoes/',
    path: '/manutencoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFornecedoresIndexRoute =
  AuthenticatedFornecedoresIndexRouteImport.update({
    id: '/fornecedores/',
    path: '/fornecedores/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipamentosIndexRoute =
  AuthenticatedEquipamentosIndexRouteImport.update({
    id: '/equipamentos/',
    path: '/equipamentos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrdensNovaRoute = AuthenticatedOrdensNovaRouteImport.update({
  id: '/ordens/nova',
  path: '/ordens/nova',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdensIdRoute = AuthenticatedOrdensIdRouteImport.update({
  id: '/ordens/$id',
  path: '/ordens/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedManutencoesIdRoute =
  AuthenticatedManutencoesIdRouteImport.update({
    id: '/manutencoes/$id',
    path: '/manutencoes/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipamentosIdRoute =
  AuthenticatedEquipamentosIdRouteImport.update({
    id: '/equipamentos/$id',
    path: '/equipamentos/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksNotificacoesRoute =
  ApiPublicHooksNotificacoesRouteImport.update({
    id: '/api/public/hooks/notificacoes',
    path: '/api/public/hooks/notificacoes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/equipamentos/$id': typeof AuthenticatedEquipamentosIdRoute
  '/manutencoes/$id': typeof AuthenticatedManutencoesIdRoute
  '/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/ordens/nova': typeof AuthenticatedOrdensNovaRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/equipamentos/': typeof AuthenticatedEquipamentosIndexRoute
  '/fornecedores/': typeof AuthenticatedFornecedoresIndexRoute
  '/manutencoes/': typeof AuthenticatedManutencoesIndexRoute
  '/ordens/': typeof AuthenticatedOrdensIndexRoute
  '/setores/': typeof AuthenticatedSetoresIndexRoute
  '/usuarios/': typeof AuthenticatedUsuariosIndexRoute
  '/api/public/hooks/notificacoes': typeof ApiPublicHooksNotificacoesRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/': typeof AuthenticatedIndexRoute
  '/equipamentos/$id': typeof AuthenticatedEquipamentosIdRoute
  '/manutencoes/$id': typeof AuthenticatedManutencoesIdRoute
  '/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/ordens/nova': typeof AuthenticatedOrdensNovaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/equipamentos': typeof AuthenticatedEquipamentosIndexRoute
  '/fornecedores': typeof AuthenticatedFornecedoresIndexRoute
  '/manutencoes': typeof AuthenticatedManutencoesIndexRoute
  '/ordens': typeof AuthenticatedOrdensIndexRoute
  '/setores': typeof AuthenticatedSetoresIndexRoute
  '/usuarios': typeof AuthenticatedUsuariosIndexRoute
  '/api/public/hooks/notificacoes': typeof ApiPublicHooksNotificacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/equipamentos/$id': typeof AuthenticatedEquipamentosIdRoute
  '/_authenticated/manutencoes/$id': typeof AuthenticatedManutencoesIdRoute
  '/_authenticated/ordens/$id': typeof AuthenticatedOrdensIdRoute
  '/_authenticated/ordens/nova': typeof AuthenticatedOrdensNovaRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/equipamentos/': typeof AuthenticatedEquipamentosIndexRoute
  '/_authenticated/fornecedores/': typeof AuthenticatedFornecedoresIndexRoute
  '/_authenticated/manutencoes/': typeof AuthenticatedManutencoesIndexRoute
  '/_authenticated/ordens/': typeof AuthenticatedOrdensIndexRoute
  '/_authenticated/setores/': typeof AuthenticatedSetoresIndexRoute
  '/_authenticated/usuarios/': typeof AuthenticatedUsuariosIndexRoute
  '/api/public/hooks/notificacoes': typeof ApiPublicHooksNotificacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/equipamentos/$id'
    | '/manutencoes/$id'
    | '/ordens/$id'
    | '/ordens/nova'
    | '/configuracoes/'
    | '/equipamentos/'
    | '/fornecedores/'
    | '/manutencoes/'
    | '/ordens/'
    | '/setores/'
    | '/usuarios/'
    | '/api/public/hooks/notificacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/equipamentos/$id'
    | '/manutencoes/$id'
    | '/ordens/$id'
    | '/ordens/nova'
    | '/configuracoes'
    | '/equipamentos'
    | '/fornecedores'
    | '/manutencoes'
    | '/ordens'
    | '/setores'
    | '/usuarios'
    | '/api/public/hooks/notificacoes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/'
    | '/_authenticated/equipamentos/$id'
    | '/_authenticated/manutencoes/$id'
    | '/_authenticated/ordens/$id'
    | '/_authenticated/ordens/nova'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/equipamentos/'
    | '/_authenticated/fornecedores/'
    | '/_authenticated/manutencoes/'
    | '/_authenticated/ordens/'
    | '/_authenticated/setores/'
    | '/_authenticated/usuarios/'
    | '/api/public/hooks/notificacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicHooksNotificacoesRoute: typeof ApiPublicHooksNotificacoesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/usuarios/': {
      id: '/_authenticated/usuarios/'
      path: '/usuarios'
      fullPath: '/usuarios/'
      preLoaderRoute: typeof AuthenticatedUsuariosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setores/': {
      id: '/_authenticated/setores/'
      path: '/setores'
      fullPath: '/setores/'
      preLoaderRoute: typeof AuthenticatedSetoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens/': {
      id: '/_authenticated/ordens/'
      path: '/ordens'
      fullPath: '/ordens/'
      preLoaderRoute: typeof AuthenticatedOrdensIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencoes/': {
      id: '/_authenticated/manutencoes/'
      path: '/manutencoes'
      fullPath: '/manutencoes/'
      preLoaderRoute: typeof AuthenticatedManutencoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fornecedores/': {
      id: '/_authenticated/fornecedores/'
      path: '/fornecedores'
      fullPath: '/fornecedores/'
      preLoaderRoute: typeof AuthenticatedFornecedoresIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos/': {
      id: '/_authenticated/equipamentos/'
      path: '/equipamentos'
      fullPath: '/equipamentos/'
      preLoaderRoute: typeof AuthenticatedEquipamentosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens/nova': {
      id: '/_authenticated/ordens/nova'
      path: '/ordens/nova'
      fullPath: '/ordens/nova'
      preLoaderRoute: typeof AuthenticatedOrdensNovaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ordens/$id': {
      id: '/_authenticated/ordens/$id'
      path: '/ordens/$id'
      fullPath: '/ordens/$id'
      preLoaderRoute: typeof AuthenticatedOrdensIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/manutencoes/$id': {
      id: '/_authenticated/manutencoes/$id'
      path: '/manutencoes/$id'
      fullPath: '/manutencoes/$id'
      preLoaderRoute: typeof AuthenticatedManutencoesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipamentos/$id': {
      id: '/_authenticated/equipamentos/$id'
      path: '/equipamentos/$id'
      fullPath: '/equipamentos/$id'
      preLoaderRoute: typeof AuthenticatedEquipamentosIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/notificacoes': {
      id: '/api/public/hooks/notificacoes'
      path: '/api/public/hooks/notificacoes'
      fullPath: '/api/public/hooks/notificacoes'
      preLoaderRoute: typeof ApiPublicHooksNotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEquipamentosIdRoute: typeof AuthenticatedEquipamentosIdRoute
  AuthenticatedManutencoesIdRoute: typeof AuthenticatedManutencoesIdRoute
  AuthenticatedOrdensIdRoute: typeof AuthenticatedOrdensIdRoute
  AuthenticatedOrdensNovaRoute: typeof AuthenticatedOrdensNovaRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
  AuthenticatedEquipamentosIndexRoute: typeof AuthenticatedEquipamentosIndexRoute
  AuthenticatedFornecedoresIndexRoute: typeof AuthenticatedFornecedoresIndexRoute
  AuthenticatedManutencoesIndexRoute: typeof AuthenticatedManutencoesIndexRoute
  AuthenticatedOrdensIndexRoute: typeof AuthenticatedOrdensIndexRoute
  AuthenticatedSetoresIndexRoute: typeof AuthenticatedSetoresIndexRoute
  AuthenticatedUsuariosIndexRoute: typeof AuthenticatedUsuariosIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEquipamentosIdRoute: AuthenticatedEquipamentosIdRoute,
  AuthenticatedManutencoesIdRoute: AuthenticatedManutencoesIdRoute,
  AuthenticatedOrdensIdRoute: AuthenticatedOrdensIdRoute,
  AuthenticatedOrdensNovaRoute: AuthenticatedOrdensNovaRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  AuthenticatedEquipamentosIndexRoute: AuthenticatedEquipamentosIndexRoute,
  AuthenticatedFornecedoresIndexRoute: AuthenticatedFornecedoresIndexRoute,
  AuthenticatedManutencoesIndexRoute: AuthenticatedManutencoesIndexRoute,
  AuthenticatedOrdensIndexRoute: AuthenticatedOrdensIndexRoute,
  AuthenticatedSetoresIndexRoute: AuthenticatedSetoresIndexRoute,
  AuthenticatedUsuariosIndexRoute: AuthenticatedUsuariosIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicHooksNotificacoesRoute: ApiPublicHooksNotificacoesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
